create table if not exists users (id integer primary key, name string, quest integer);
create table if not exists floors (name string primary key, category string);
insert into floors(name, category) values
  ("Lobby", "none"),
  ("Residential", "none"),
  ("Airline Food", "Food"),
  ("Asian Cuisine", "Food"),
  ("Bakery", "Food"),
  ("BBQ Place", "Food"),
  ("Cheese Shop", "Food"),
  ("Coffee House", "Food"),
  ("Diner", "Food"),
  ("Donut Shop", "Food"),
  ("Fancy Cuisine", "Food"),
  ("Frozen Yogurt", "Food"),
  ("Hot Dog Joint", "Food"),
  ("Italian Food", "Food"),
  ("Mexican Food", "Food"),
  ("Pancake House", "Food"),
  ("Pizza Place", "Food"),
  ("Pub", "Food"),
  ("Scoops", "Food"),
  ("Seafood", "Food"),
  ("Sky Burger", "Food"),
  ("Smoothie Shop", "Food"),
  ("Sub Shop", "Food"),
  ("Sushi Bar", "Food"),
  ("Tea House", "Food"),
  ("Vegan Food", "Food"),
  ("Bank", "Service"),
  ("Barber Shop", "Service"),
  ("Courthouse", "Service"),
  ("Day Spa", "Service"),
  ("Dentists Office", "Service"),
  ("Doctors Office", "Service"),
  ("Fire Station", "Service"),
  ("Fortune Teller", "Service"),
  ("Health Club", "Service"),
  ("Laundromat", "Service"),
  ("Martial Arts", "Service"),
  ("Mechanic", "Service"),
  ("Optometrist", "Service"),
  ("Pharmacy", "Service"),
  ("Plumber", "Service"),
  ("Private Eye", "Service"),
  ("Recycling", "Service"),
  ("Security Office", "Service"),
  ("Ship & Print", "Service"),
  ("Stables", "Service"),
  ("Stock Exchange", "Service"),
  ("Travel Agency", "Service"),
  ("Tutoring Center", "Service"),
  ("Wedding Chapel", "Service"),
  ("Aquarium", "Recreation"),
  ("Arcade", "Recreation"),
  ("Archery Range", "Recreation"),
  ("Billiard Hall", "Recreation"),
  ("Bowling Alley", "Recreation"),
  ("Casino", "Recreation"),
  ("Cineplex", "Recreation"),
  ("Circus", "Recreation"),
  ("Comedy Club", "Recreation"),
  ("Cyber Cafe", "Recreation"),
  ("Golf Sim", "Recreation"),
  ("Haunted House", "Recreation"),
  ("Karaoke Club", "Recreation"),
  ("Mini Golf", "Recreation"),
  ("Museum", "Recreation"),
  ("Night Club", "Recreation"),
  ("Park", "Recreation"),
  ("Planetarium", "Recreation"),
  ("Paintball Arena", "Recreation"),
  ("Racquetball", "Recreation"),
  ("Rock Climbing", "Recreation"),
  ("Theater", "Recreation"),
  ("Video Rental", "Recreation"),
  ("Volleyball Club", "Recreation"),
  ("Auto Dealer", "Retail"),
  ("Bike Shop", "Retail"),
  ("Book Store", "Retail"),
  ("Candle Shop", "Retail"),
  ("Comic Store", "Retail"),
  ("Fabric Shop", "Retail"),
  ("Furniture Store", "Retail"),
  ("Game Store", "Retail"),
  ("Grocery Store", "Retail"),
  ("Hat Shop", "Retail"),
  ("Home Supply", "Retail"),
  ("Jewelry Store", "Retail"),
  ("Mapple Store", "Retail"),
  ("Mens Fashion", "Retail"),
  ("Music Store", "Retail"),
  ("Pet Shop", "Retail"),
  ("Plant Nursery", "Retail"),
  ("Record Shop", "Retail"),
  ("Robot Store", "Retail"),
  ("Shoe Store", "Retail"),
  ("Surf Shop", "Retail"),
  ("Tech Store", "Retail"),
  ("Toy Store", "Retail"),
  ("Womens Fashion", "Retail"),
  ("Ad Agency", "Creative"),
  ("Animation Studio", "Creative"),
  ("Architect Office", "Creative"),
  ("Art Studio", "Creative"),
  ("Cake Studio", "Creative"),
  ("Chocolatier", "Creative"),
  ("Clockmaker", "Creative"),
  ("Costume Shop", "Creative"),
  ("Fashion Studio", "Creative"),
  ("Film Studio", "Creative"),
  ("Floral Studio", "Creative"),
  ("Game Studio", "Creative"),
  ("Glass Studio", "Creative"),
  ("Graphic Design", "Creative"),
  ("Laboratory", "Creative"),
  ("Photo Studio", "Creative"),
  ("Pottery Studio", "Creative"),
  ("Recording Studio", "Creative"),
  ("Sculpting Studio", "Creative"),
  ("Soda Brewery", "Creative"),
  ("Software Studio", "Creative"),
  ("Tattoo Parlor", "Creative"),
  ("Tv Studio", "Creative"),
  ("Wood Shop", "Creative");
create table if not exists towers (user integer, story integer, floor string);
create table if not exists missions (name string, part1 integer, part2 integer, part3 integer);
insert into missions(name, part1, part2, part3) values
  ("Beware Of Dog", "Architect Office", "Game Studio", null),
  ("Soy Loco", "Asian Cuisine", "Vegan Food", null),
  ("Presidents Day 2012", "Auto Dealer", "Furniture Store", null),
  ("Santa's Swap", "Bakery", "Toy Store", null),
  ("One Big Score", "Bank", "Casino", null),
  ("Save The Planet", "Bike Shop", "Vegan Food", null),
  ("Fathers Day 2012", "Bike Shop", "Animation Studio", null),
  ("Summer School", "Book Store", "Tutoring Center", null),
  ("The Dude Abides", "Bowling Alley", "Pub", null),
  ("Beat the Heat", "Coffee House", "Pub", "Soda Brewery"),
  ("Hot Trends", "Coffee House", "Record Shop", null),
  ("April Fools 2012", "Comedy Club", "Billiard Hall", null),
  ("Comic Convention", "Comic Store", "Pharmacy", null),
  ("Valentines 2012", "Day Spa", "Floral Studio", null),
  ("Mothers Day 2012", "Day Spa", "Womens Fashion", null),
  ("Award Night", "Dentists Office", "Barber Shop", null),
  ("On The Beat", "Diner", "Donut Shop", null),
  ("Team Tiny", "Doctors Office", "Health Club", null),
  ("Thanksgiving Feast", "Fancy Cuisine", "Travel Agency", null),
  ("Prom Night", "Floral Studio", "Mens Fashion", null),
  ("Spring Time", "Floral Studio", "Tattoo Parlor", null),
  ("First Apartment", "Furniture Store", "Pottery Studio", null),
  ("Superstar", "Graphic Design", "Record Shop", null),
  ("Frog Fundraiser", "Museum", "Fancy Cuisine", null),
  ("New Years 2012", "Night Club", "Health Club", null),
  ("Nasty Bug", "Pharmacy", "Diner", null),
  ("A Baby Is Born", "Photo Studio", "Toy Store", null),
  ("Mars Curiosity", "Planetarium", "Laboratory", null),
  ("Earth Day 2012", "Plant Nursery", "Recycling", null),
  ("Last Night", "Pub", "Tattoo Parlor", null),
  ("A Bit Fishy", "Sushi Bar", "Mexican Food", null),
  ("A Day At The Beach", "Shoe Store", "Volleyball Club", "Frozen Yogurt"),
  ("Back To Wiz School", "Fortune Teller", "Laboratory", "Book Store"),
  ("Baseball Playoffs", "Pub", "Cineplex", null),
  ("Bithoven's Symphony", "Wood Shop", "Music Store", null),
  ("Bit Trek TNG", "Animation Studio", "Tech Store", null),
  ("Bits In Space", "Toy Store", "Planetarium", null),
  ("Canadian Thanks 2012", "Vegan Food", "Fancy Cuisine", null),
  ("Cinco De Mayo 2012", "Mexican Food", "Music Store", null),
  ("Cowabunga", "Laboratory", "Martial Arts", "Pizza Place"),
  ("Fire Drill", "Security Office", "Architect Office", null),
  ("Labor Day 2012", "Auto Dealer", "Security Office", null),
  ("London Games", "Volleyball Club", "Shoe Store", "Racquetball"),
  ("Music Festival", "Music Store", "Recording Studio", null),
  ("Myphone 5 Launch", "Mapple Store", "TV Studio", null),
  ("One Mad Tea Party", "Tea House", "Bakery", null),
  ("Pocket Planes", "Travel Agency", "Pub", null),
  ("Self Defense", "Martial Arts", "Security Office", null),
  ("St. Patty's 2012", "Tea House", "Glass Studio", null),
  ("Summer Vacation", "Travel Agency", "Scoops", null),
  ("The Big Game", "Tech Store", "Pub", null),
  ("The Heist", "Security Office", "Security Office", null),
  ("Tiny Taxes", "Tutoring Center", "Bank", null),
  ("Tower Watch", "Security Office", "Private Eye", null),
  ("Wedding Season", "Wedding Chapel", "Floral Studio", null),
  ("Mimecon 2012", "Day Spa", "Theater", null),
  ("Halloween 2012", "Chocolatier", "Laboratory", "Haunted House"),
  ("Election 2012", "Ad Agency", "TV Studio", null),
  ("North Pole Recon", "Private Eye", "Fortune Teller", null),
  ("Board Meeting", "Sub Shop", "Bakery", "Coffee House"),
  ("Valentines 2014", "Archery Range", "Chocolatier", null),
  ("National Pig Day", "Hat Shop", "Photo Studio", null),
  ("St. Patty's Day 2013", "Bakery", "Hat Shop", null),
  ("Tower Taxes", "Tutoring Center", "Bank", null),
  ("Arbor Day 2013", "Plant Nursery", "Sub Shop", null),
  ("Cinco De Mayo 2013", "Mexican Food", "Music Store", null),
  ("Mothers Day 2013", "Womens Fashion", "Jewelry Store", "Day Spa"),
  ("Armed Forces Day 2013", "Toy Store", "Barber Shop", "Security Office"),
  ("Memorial Day 2013", "Music Store", "Floral Studio", null),
  ("JFK's Birthday", "Toy Store", "TV Studio", null),
  ("Feel the Earth", "Bike Shop", "Recycling", "Recycling"),
  ("Flag Day 2013", "Fabric Shop", "Fabric Shop", null),
  ("Fathers Day 2013", "Tech Store", "Animation Studio", null),
  ("Solstice", "Shoe Store", "Park", null),
  ("Independence Day '13", "Hot Dog Joint", "Hat Shop", null),
  ("Aboriginal Day ", "Archery Range", "Costume Shop", null),
  ("Moon Day", "Toy Store", "Scoops", null),
  ("Pioneer Day", "Mechanic", "Tech Store", null),
  ("Book Lovers Day", "Wood Shop", "Book Store", null),
  ("Summer Vacation '13", "Surf Shop", "Smoothie Shop", null),
  ("Relaxation Day", "Day Spa", "Candle Shop", null),
  ("Aviation Day", "Travel Agency", "Pub", null),
  ("Senior Citizens Day", "Park", "Womens Fashion", "Mens Fashion"),
  ("Labor Day '13", "Plumber", "Fire Station", null),
  ("Programmers' Day", "Tech Store", "Software Studio", null),
  ("Oktoberfest '13", "Pub", "Clockmaker", null),
  ("Confucious Day", "Martial Arts", "Asian Cuisine", null),
  ("World Vegetarian Day", "Vegan Food", "Plant Nursery", null),
  ("Fire Prevention Day", "Fire Station", "Ad Agency", null);
create table if not exists completed(mission string, user integer);