PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE users (id integer primary key, name string, quest integer);
CREATE TABLE towers (user integer, story integer, floor string);
CREATE TABLE completed(mission string, user integer);
CREATE TABLE floors (name string primary key, category string);
INSERT INTO "floors" VALUES('Lobby','none');
INSERT INTO "floors" VALUES('Residential','none');
INSERT INTO "floors" VALUES('Airline Food','Food');
INSERT INTO "floors" VALUES('Asian Cuisine','Food');
INSERT INTO "floors" VALUES('Bakery','Food');
INSERT INTO "floors" VALUES('BBQ Place','Food');
INSERT INTO "floors" VALUES('Cheese Shop','Food');
INSERT INTO "floors" VALUES('Coffee House','Food');
INSERT INTO "floors" VALUES('Diner','Food');
INSERT INTO "floors" VALUES('Donut Shop','Food');
INSERT INTO "floors" VALUES('Fancy Cuisine','Food');
INSERT INTO "floors" VALUES('Frozen Yogurt','Food');
INSERT INTO "floors" VALUES('Hot Dog Joint','Food');
INSERT INTO "floors" VALUES('Italian Food','Food');
INSERT INTO "floors" VALUES('Mexican Food','Food');
INSERT INTO "floors" VALUES('Pancake House','Food');
INSERT INTO "floors" VALUES('Pizza Place','Food');
INSERT INTO "floors" VALUES('Pub','Food');
INSERT INTO "floors" VALUES('Scoops','Food');
INSERT INTO "floors" VALUES('Seafood','Food');
INSERT INTO "floors" VALUES('Sky Burger','Food');
INSERT INTO "floors" VALUES('Smoothie Shop','Food');
INSERT INTO "floors" VALUES('Sub Shop','Food');
INSERT INTO "floors" VALUES('Sushi Bar','Food');
INSERT INTO "floors" VALUES('Tea House','Food');
INSERT INTO "floors" VALUES('Vegan Food','Food');
INSERT INTO "floors" VALUES('Bank','Service');
INSERT INTO "floors" VALUES('Barber Shop','Service');
INSERT INTO "floors" VALUES('Courthouse','Service');
INSERT INTO "floors" VALUES('Day Spa','Service');
INSERT INTO "floors" VALUES('Dentists Office','Service');
INSERT INTO "floors" VALUES('Doctors Office','Service');
INSERT INTO "floors" VALUES('Fire Station','Service');
INSERT INTO "floors" VALUES('Fortune Teller','Service');
INSERT INTO "floors" VALUES('Health Club','Service');
INSERT INTO "floors" VALUES('Laundromat','Service');
INSERT INTO "floors" VALUES('Martial Arts','Service');
INSERT INTO "floors" VALUES('Mechanic','Service');
INSERT INTO "floors" VALUES('Optometrist','Service');
INSERT INTO "floors" VALUES('Pharmacy','Service');
INSERT INTO "floors" VALUES('Plumber','Service');
INSERT INTO "floors" VALUES('Private Eye','Service');
INSERT INTO "floors" VALUES('Recycling','Service');
INSERT INTO "floors" VALUES('Security Office','Service');
INSERT INTO "floors" VALUES('Ship & Print','Service');
INSERT INTO "floors" VALUES('Stables','Service');
INSERT INTO "floors" VALUES('Stock Exchange','Service');
INSERT INTO "floors" VALUES('Travel Agency','Service');
INSERT INTO "floors" VALUES('Tutoring Center','Service');
INSERT INTO "floors" VALUES('Wedding Chapel','Service');
INSERT INTO "floors" VALUES('Aquarium','Recreation');
INSERT INTO "floors" VALUES('Arcade','Recreation');
INSERT INTO "floors" VALUES('Archery Range','Recreation');
INSERT INTO "floors" VALUES('Billiard Hall','Recreation');
INSERT INTO "floors" VALUES('Bowling Alley','Recreation');
INSERT INTO "floors" VALUES('Casino','Recreation');
INSERT INTO "floors" VALUES('Cineplex','Recreation');
INSERT INTO "floors" VALUES('Circus','Recreation');
INSERT INTO "floors" VALUES('Comedy Club','Recreation');
INSERT INTO "floors" VALUES('Cyber Cafe','Recreation');
INSERT INTO "floors" VALUES('Golf Sim','Recreation');
INSERT INTO "floors" VALUES('Haunted House','Recreation');
INSERT INTO "floors" VALUES('Karaoke Club','Recreation');
INSERT INTO "floors" VALUES('Mini Golf','Recreation');
INSERT INTO "floors" VALUES('Museum','Recreation');
INSERT INTO "floors" VALUES('Night Club','Recreation');
INSERT INTO "floors" VALUES('Park','Recreation');
INSERT INTO "floors" VALUES('Planetarium','Recreation');
INSERT INTO "floors" VALUES('Paintball Arena','Recreation');
INSERT INTO "floors" VALUES('Racquetball','Recreation');
INSERT INTO "floors" VALUES('Rock Climbing','Recreation');
INSERT INTO "floors" VALUES('Theater','Recreation');
INSERT INTO "floors" VALUES('Video Rental','Recreation');
INSERT INTO "floors" VALUES('Volleyball Club','Recreation');
INSERT INTO "floors" VALUES('Auto Dealer','Retail');
INSERT INTO "floors" VALUES('Bike Shop','Retail');
INSERT INTO "floors" VALUES('Book Store','Retail');
INSERT INTO "floors" VALUES('Candle Shop','Retail');
INSERT INTO "floors" VALUES('Comic Store','Retail');
INSERT INTO "floors" VALUES('Fabric Shop','Retail');
INSERT INTO "floors" VALUES('Furniture Store','Retail');
INSERT INTO "floors" VALUES('Game Store','Retail');
INSERT INTO "floors" VALUES('Grocery Store','Retail');
INSERT INTO "floors" VALUES('Hat Shop','Retail');
INSERT INTO "floors" VALUES('Home Supply','Retail');
INSERT INTO "floors" VALUES('Jewelry Store','Retail');
INSERT INTO "floors" VALUES('Mapple Store','Retail');
INSERT INTO "floors" VALUES('Mens Fashion','Retail');
INSERT INTO "floors" VALUES('Music Store','Retail');
INSERT INTO "floors" VALUES('Pet Shop','Retail');
INSERT INTO "floors" VALUES('Plant Nursery','Retail');
INSERT INTO "floors" VALUES('Record Shop','Retail');
INSERT INTO "floors" VALUES('Robot Store','Retail');
INSERT INTO "floors" VALUES('Shoe Store','Retail');
INSERT INTO "floors" VALUES('Surf Shop','Retail');
INSERT INTO "floors" VALUES('Tech Store','Retail');
INSERT INTO "floors" VALUES('Toy Store','Retail');
INSERT INTO "floors" VALUES('Womens Fashion','Retail');
INSERT INTO "floors" VALUES('Ad Agency','Creative');
INSERT INTO "floors" VALUES('Animation Studio','Creative');
INSERT INTO "floors" VALUES('Architect Office','Creative');
INSERT INTO "floors" VALUES('Art Studio','Creative');
INSERT INTO "floors" VALUES('Cake Studio','Creative');
INSERT INTO "floors" VALUES('Chocolatier','Creative');
INSERT INTO "floors" VALUES('Clockmaker','Creative');
INSERT INTO "floors" VALUES('Costume Shop','Creative');
INSERT INTO "floors" VALUES('Fashion Studio','Creative');
INSERT INTO "floors" VALUES('Film Studio','Creative');
INSERT INTO "floors" VALUES('Floral Studio','Creative');
INSERT INTO "floors" VALUES('Game Studio','Creative');
INSERT INTO "floors" VALUES('Glass Studio','Creative');
INSERT INTO "floors" VALUES('Graphic Design','Creative');
INSERT INTO "floors" VALUES('Laboratory','Creative');
INSERT INTO "floors" VALUES('Photo Studio','Creative');
INSERT INTO "floors" VALUES('Pottery Studio','Creative');
INSERT INTO "floors" VALUES('Recording Studio','Creative');
INSERT INTO "floors" VALUES('Sculpting Studio','Creative');
INSERT INTO "floors" VALUES('Soda Brewery','Creative');
INSERT INTO "floors" VALUES('Software Studio','Creative');
INSERT INTO "floors" VALUES('Tattoo Parlor','Creative');
INSERT INTO "floors" VALUES('Tv Studio','Creative');
INSERT INTO "floors" VALUES('Wood Shop','Creative');
CREATE TABLE missions (name string, part1 integer, part2 integer, part3 integer);
INSERT INTO "missions" VALUES('Beware Of Dog','Architect Office','Game Studio',NULL);
INSERT INTO "missions" VALUES('Soy Loco','Asian Cuisine','Vegan Food',NULL);
INSERT INTO "missions" VALUES('Presidents Day 2012','Auto Dealer','Furniture Store',NULL);
INSERT INTO "missions" VALUES('Santa''s Swap','Bakery','Toy Store',NULL);
INSERT INTO "missions" VALUES('One Big Score','Bank','Casino',NULL);
INSERT INTO "missions" VALUES('Save The Planet','Bike Shop','Vegan Food',NULL);
INSERT INTO "missions" VALUES('Fathers Day 2012','Bike Shop','Animation Studio',NULL);
INSERT INTO "missions" VALUES('Summer School','Book Store','Tutoring Center',NULL);
INSERT INTO "missions" VALUES('The Dude Abides','Bowling Alley','Pub',NULL);
INSERT INTO "missions" VALUES('Beat the Heat','Coffee House','Pub','Soda Brewery');
INSERT INTO "missions" VALUES('Hot Trends','Coffee House','Record Shop',NULL);
INSERT INTO "missions" VALUES('April Fools 2012','Comedy Club','Billiard Hall',NULL);
INSERT INTO "missions" VALUES('Comic Convention','Comic Store','Pharmacy',NULL);
INSERT INTO "missions" VALUES('Valentines 2012','Day Spa','Floral Studio',NULL);
INSERT INTO "missions" VALUES('Mothers Day 2012','Day Spa','Womens Fashion',NULL);
INSERT INTO "missions" VALUES('Award Night','Dentists Office','Barber Shop',NULL);
INSERT INTO "missions" VALUES('On The Beat','Diner','Donut Shop',NULL);
INSERT INTO "missions" VALUES('Team Tiny','Doctors Office','Health Club',NULL);
INSERT INTO "missions" VALUES('Thanksgiving Feast','Fancy Cuisine','Travel Agency',NULL);
INSERT INTO "missions" VALUES('Prom Night','Floral Studio','Mens Fashion',NULL);
INSERT INTO "missions" VALUES('Spring Time','Floral Studio','Tattoo Parlor',NULL);
INSERT INTO "missions" VALUES('First Apartment','Furniture Store','Pottery Studio',NULL);
INSERT INTO "missions" VALUES('Superstar','Graphic Design','Record Shop',NULL);
INSERT INTO "missions" VALUES('Frog Fundraiser','Museum','Fancy Cuisine',NULL);
INSERT INTO "missions" VALUES('New Years 2012','Night Club','Health Club',NULL);
INSERT INTO "missions" VALUES('Nasty Bug','Pharmacy','Diner',NULL);
INSERT INTO "missions" VALUES('A Baby Is Born','Photo Studio','Toy Store',NULL);
INSERT INTO "missions" VALUES('Mars Curiosity','Planetarium','Laboratory',NULL);
INSERT INTO "missions" VALUES('Earth Day 2012','Plant Nursery','Recycling',NULL);
INSERT INTO "missions" VALUES('Last Night','Pub','Tattoo Parlor',NULL);
INSERT INTO "missions" VALUES('A Bit Fishy','Sushi Bar','Mexican Food',NULL);
INSERT INTO "missions" VALUES('A Day At The Beach','Shoe Store','Volleyball Club','Frozen Yogurt');
INSERT INTO "missions" VALUES('Back To Wiz School','Fortune Teller','Laboratory','Book Store');
INSERT INTO "missions" VALUES('Baseball Playoffs','Pub','Cineplex',NULL);
INSERT INTO "missions" VALUES('Bithoven''s Symphony','Wood Shop','Music Store',NULL);
INSERT INTO "missions" VALUES('Bit Trek TNG','Animation Studio','Tech Store',NULL);
INSERT INTO "missions" VALUES('Bits In Space','Toy Store','Planetarium',NULL);
INSERT INTO "missions" VALUES('Canadian Thanks 2012','Vegan Food','Fancy Cuisine',NULL);
INSERT INTO "missions" VALUES('Cinco De Mayo 2012','Mexican Food','Music Store',NULL);
INSERT INTO "missions" VALUES('Cowabunga','Laboratory','Martial Arts','Pizza Place');
INSERT INTO "missions" VALUES('Fire Drill','Security Office','Architect Office',NULL);
INSERT INTO "missions" VALUES('Labor Day 2012','Auto Dealer','Security Office',NULL);
INSERT INTO "missions" VALUES('London Games','Volleyball Club','Shoe Store','Racquetball');
INSERT INTO "missions" VALUES('Music Festival','Music Store','Recording Studio',NULL);
INSERT INTO "missions" VALUES('Myphone 5 Launch','Mapple Store','TV Studio',NULL);
INSERT INTO "missions" VALUES('One Mad Tea Party','Tea House','Bakery',NULL);
INSERT INTO "missions" VALUES('Pocket Planes','Travel Agency','Pub',NULL);
INSERT INTO "missions" VALUES('Self Defense','Martial Arts','Security Office',NULL);
INSERT INTO "missions" VALUES('St. Patty''s 2012','Tea House','Glass Studio',NULL);
INSERT INTO "missions" VALUES('Summer Vacation','Travel Agency','Scoops',NULL);
INSERT INTO "missions" VALUES('The Big Game','Tech Store','Pub',NULL);
INSERT INTO "missions" VALUES('The Heist','Security Office','Security Office',NULL);
INSERT INTO "missions" VALUES('Tiny Taxes','Tutoring Center','Bank',NULL);
INSERT INTO "missions" VALUES('Tower Watch','Security Office','Private Eye',NULL);
INSERT INTO "missions" VALUES('Wedding Season','Wedding Chapel','Floral Studio',NULL);
INSERT INTO "missions" VALUES('Mimecon 2012','Day Spa','Theater',NULL);
INSERT INTO "missions" VALUES('Halloween 2012','Chocolatier','Laboratory','Haunted House');
INSERT INTO "missions" VALUES('Election 2012','Ad Agency','TV Studio',NULL);
INSERT INTO "missions" VALUES('North Pole Recon','Private Eye','Fortune Teller',NULL);
INSERT INTO "missions" VALUES('Board Meeting','Sub Shop','Bakery','Coffee House');
INSERT INTO "missions" VALUES('Valentines 2014','Archery Range','Chocolatier',NULL);
INSERT INTO "missions" VALUES('National Pig Day','Hat Shop','Photo Studio',NULL);
INSERT INTO "missions" VALUES('St. Patty''s Day 2013','Bakery','Hat Shop',NULL);
INSERT INTO "missions" VALUES('Tower Taxes','Tutoring Center','Bank',NULL);
INSERT INTO "missions" VALUES('Arbor Day 2013','Plant Nursery','Sub Shop',NULL);
INSERT INTO "missions" VALUES('Cinco De Mayo 2013','Mexican Food','Music Store',NULL);
INSERT INTO "missions" VALUES('Mothers Day 2013','Womens Fashion','Jewelry Store','Day Spa');
INSERT INTO "missions" VALUES('Armed Forces Day 2013','Toy Store','Barber Shop','Security Office');
INSERT INTO "missions" VALUES('Memorial Day 2013','Music Store','Floral Studio',NULL);
INSERT INTO "missions" VALUES('JFK''s Birthday','Toy Store','TV Studio',NULL);
INSERT INTO "missions" VALUES('Feel the Earth','Bike Shop','Recycling','Recycling');
INSERT INTO "missions" VALUES('Flag Day 2013','Fabric Shop','Fabric Shop',NULL);
INSERT INTO "missions" VALUES('Fathers Day 2013','Tech Store','Animation Studio',NULL);
INSERT INTO "missions" VALUES('Solstice','Shoe Store','Park',NULL);
INSERT INTO "missions" VALUES('Independence Day ''13','Hot Dog Joint','Hat Shop',NULL);
INSERT INTO "missions" VALUES('Aboriginal Day ','Archery Range','Costume Shop',NULL);
INSERT INTO "missions" VALUES('Moon Day','Toy Store','Scoops',NULL);
INSERT INTO "missions" VALUES('Pioneer Day','Mechanic','Tech Store',NULL);
INSERT INTO "missions" VALUES('Book Lovers Day','Wood Shop','Book Store',NULL);
INSERT INTO "missions" VALUES('Summer Vacation ''13','Surf Shop','Smoothie Shop',NULL);
INSERT INTO "missions" VALUES('Relaxation Day','Day Spa','Candle Shop',NULL);
INSERT INTO "missions" VALUES('Aviation Day','Travel Agency','Pub',NULL);
INSERT INTO "missions" VALUES('Senior Citizens Day','Park','Womens Fashion','Mens Fashion');
INSERT INTO "missions" VALUES('Labor Day ''13','Plumber','Fire Station',NULL);
INSERT INTO "missions" VALUES('Programmers'' Day','Tech Store','Software Studio',NULL);
INSERT INTO "missions" VALUES('Oktoberfest ''13','Pub','Clockmaker',NULL);
INSERT INTO "missions" VALUES('Confucious Day','Martial Arts','Asian Cuisine',NULL);
INSERT INTO "missions" VALUES('World Vegetarian Day','Vegan Food','Plant Nursery',NULL);
INSERT INTO "missions" VALUES('Fire Prevention Day','Fire Station','Ad Agency',NULL);
INSERT INTO "missions" VALUES('Beware Of Dog','Architect Office','Game Studio',NULL);
INSERT INTO "missions" VALUES('Soy Loco','Asian Cuisine','Vegan Food',NULL);
INSERT INTO "missions" VALUES('Presidents Day 2012','Auto Dealer','Furniture Store',NULL);
INSERT INTO "missions" VALUES('Santa''s Swap','Bakery','Toy Store',NULL);
INSERT INTO "missions" VALUES('One Big Score','Bank','Casino',NULL);
INSERT INTO "missions" VALUES('Save The Planet','Bike Shop','Vegan Food',NULL);
INSERT INTO "missions" VALUES('Fathers Day 2012','Bike Shop','Animation Studio',NULL);
INSERT INTO "missions" VALUES('Summer School','Book Store','Tutoring Center',NULL);
INSERT INTO "missions" VALUES('The Dude Abides','Bowling Alley','Pub',NULL);
INSERT INTO "missions" VALUES('Beat the Heat','Coffee House','Pub','Soda Brewery');
INSERT INTO "missions" VALUES('Hot Trends','Coffee House','Record Shop',NULL);
INSERT INTO "missions" VALUES('April Fools 2012','Comedy Club','Billiard Hall',NULL);
INSERT INTO "missions" VALUES('Comic Convention','Comic Store','Pharmacy',NULL);
INSERT INTO "missions" VALUES('Valentines 2012','Day Spa','Floral Studio',NULL);
INSERT INTO "missions" VALUES('Mothers Day 2012','Day Spa','Womens Fashion',NULL);
INSERT INTO "missions" VALUES('Award Night','Dentists Office','Barber Shop',NULL);
INSERT INTO "missions" VALUES('On The Beat','Diner','Donut Shop',NULL);
INSERT INTO "missions" VALUES('Team Tiny','Doctors Office','Health Club',NULL);
INSERT INTO "missions" VALUES('Thanksgiving Feast','Fancy Cuisine','Travel Agency',NULL);
INSERT INTO "missions" VALUES('Prom Night','Floral Studio','Mens Fashion',NULL);
INSERT INTO "missions" VALUES('Spring Time','Floral Studio','Tattoo Parlor',NULL);
INSERT INTO "missions" VALUES('First Apartment','Furniture Store','Pottery Studio',NULL);
INSERT INTO "missions" VALUES('Superstar','Graphic Design','Record Shop',NULL);
INSERT INTO "missions" VALUES('Frog Fundraiser','Museum','Fancy Cuisine',NULL);
INSERT INTO "missions" VALUES('New Years 2012','Night Club','Health Club',NULL);
INSERT INTO "missions" VALUES('Nasty Bug','Pharmacy','Diner',NULL);
INSERT INTO "missions" VALUES('A Baby Is Born','Photo Studio','Toy Store',NULL);
INSERT INTO "missions" VALUES('Mars Curiosity','Planetarium','Laboratory',NULL);
INSERT INTO "missions" VALUES('Earth Day 2012','Plant Nursery','Recycling',NULL);
INSERT INTO "missions" VALUES('Last Night','Pub','Tattoo Parlor',NULL);
INSERT INTO "missions" VALUES('A Bit Fishy','Sushi Bar','Mexican Food',NULL);
INSERT INTO "missions" VALUES('A Day At The Beach','Shoe Store','Volleyball Club','Frozen Yogurt');
INSERT INTO "missions" VALUES('Back To Wiz School','Fortune Teller','Laboratory','Book Store');
INSERT INTO "missions" VALUES('Baseball Playoffs','Pub','Cineplex',NULL);
INSERT INTO "missions" VALUES('Bithoven''s Symphony','Wood Shop','Music Store',NULL);
INSERT INTO "missions" VALUES('Bit Trek TNG','Animation Studio','Tech Store',NULL);
INSERT INTO "missions" VALUES('Bits In Space','Toy Store','Planetarium',NULL);
INSERT INTO "missions" VALUES('Canadian Thanks 2012','Vegan Food','Fancy Cuisine',NULL);
INSERT INTO "missions" VALUES('Cinco De Mayo 2012','Mexican Food','Music Store',NULL);
INSERT INTO "missions" VALUES('Cowabunga','Laboratory','Martial Arts','Pizza Place');
INSERT INTO "missions" VALUES('Fire Drill','Security Office','Architect Office',NULL);
INSERT INTO "missions" VALUES('Labor Day 2012','Auto Dealer','Security Office',NULL);
INSERT INTO "missions" VALUES('London Games','Volleyball Club','Shoe Store','Racquetball');
INSERT INTO "missions" VALUES('Music Festival','Music Store','Recording Studio',NULL);
INSERT INTO "missions" VALUES('Myphone 5 Launch','Mapple Store','TV Studio',NULL);
INSERT INTO "missions" VALUES('One Mad Tea Party','Tea House','Bakery',NULL);
INSERT INTO "missions" VALUES('Pocket Planes','Travel Agency','Pub',NULL);
INSERT INTO "missions" VALUES('Self Defense','Martial Arts','Security Office',NULL);
INSERT INTO "missions" VALUES('St. Patty''s 2012','Tea House','Glass Studio',NULL);
INSERT INTO "missions" VALUES('Summer Vacation','Travel Agency','Scoops',NULL);
INSERT INTO "missions" VALUES('The Big Game','Tech Store','Pub',NULL);
INSERT INTO "missions" VALUES('The Heist','Security Office','Security Office',NULL);
INSERT INTO "missions" VALUES('Tiny Taxes','Tutoring Center','Bank',NULL);
INSERT INTO "missions" VALUES('Tower Watch','Security Office','Private Eye',NULL);
INSERT INTO "missions" VALUES('Wedding Season','Wedding Chapel','Floral Studio',NULL);
INSERT INTO "missions" VALUES('Mimecon 2012','Day Spa','Theater',NULL);
INSERT INTO "missions" VALUES('Halloween 2012','Chocolatier','Laboratory','Haunted House');
INSERT INTO "missions" VALUES('Election 2012','Ad Agency','TV Studio',NULL);
INSERT INTO "missions" VALUES('North Pole Recon','Private Eye','Fortune Teller',NULL);
INSERT INTO "missions" VALUES('Board Meeting','Sub Shop','Bakery','Coffee House');
INSERT INTO "missions" VALUES('Valentines 2014','Archery Range','Chocolatier',NULL);
INSERT INTO "missions" VALUES('National Pig Day','Hat Shop','Photo Studio',NULL);
INSERT INTO "missions" VALUES('St. Patty''s Day 2013','Bakery','Hat Shop',NULL);
INSERT INTO "missions" VALUES('Tower Taxes','Tutoring Center','Bank',NULL);
INSERT INTO "missions" VALUES('Arbor Day 2013','Plant Nursery','Sub Shop',NULL);
INSERT INTO "missions" VALUES('Cinco De Mayo 2013','Mexican Food','Music Store',NULL);
INSERT INTO "missions" VALUES('Mothers Day 2013','Womens Fashion','Jewelry Store','Day Spa');
INSERT INTO "missions" VALUES('Armed Forces Day 2013','Toy Store','Barber Shop','Security Office');
INSERT INTO "missions" VALUES('Memorial Day 2013','Music Store','Floral Studio',NULL);
INSERT INTO "missions" VALUES('JFK''s Birthday','Toy Store','TV Studio',NULL);
INSERT INTO "missions" VALUES('Feel the Earth','Bike Shop','Recycling','Recycling');
INSERT INTO "missions" VALUES('Flag Day 2013','Fabric Shop','Fabric Shop',NULL);
INSERT INTO "missions" VALUES('Fathers Day 2013','Tech Store','Animation Studio',NULL);
INSERT INTO "missions" VALUES('Solstice','Shoe Store','Park',NULL);
INSERT INTO "missions" VALUES('Independence Day ''13','Hot Dog Joint','Hat Shop',NULL);
INSERT INTO "missions" VALUES('Aboriginal Day ','Archery Range','Costume Shop',NULL);
INSERT INTO "missions" VALUES('Moon Day','Toy Store','Scoops',NULL);
INSERT INTO "missions" VALUES('Pioneer Day','Mechanic','Tech Store',NULL);
INSERT INTO "missions" VALUES('Book Lovers Day','Wood Shop','Book Store',NULL);
INSERT INTO "missions" VALUES('Summer Vacation ''13','Surf Shop','Smoothie Shop',NULL);
INSERT INTO "missions" VALUES('Relaxation Day','Day Spa','Candle Shop',NULL);
INSERT INTO "missions" VALUES('Aviation Day','Travel Agency','Pub',NULL);
INSERT INTO "missions" VALUES('Senior Citizens Day','Park','Womens Fashion','Mens Fashion');
INSERT INTO "missions" VALUES('Labor Day ''13','Plumber','Fire Station',NULL);
INSERT INTO "missions" VALUES('Programmers'' Day','Tech Store','Software Studio',NULL);
INSERT INTO "missions" VALUES('Oktoberfest ''13','Pub','Clockmaker',NULL);
INSERT INTO "missions" VALUES('Confucious Day','Martial Arts','Asian Cuisine',NULL);
INSERT INTO "missions" VALUES('World Vegetarian Day','Vegan Food','Plant Nursery',NULL);
INSERT INTO "missions" VALUES('Fire Prevention Day','Fire Station','Ad Agency',NULL);
INSERT INTO "missions" VALUES('Beware Of Dog','Architect Office','Game Studio',NULL);
INSERT INTO "missions" VALUES('Soy Loco','Asian Cuisine','Vegan Food',NULL);
INSERT INTO "missions" VALUES('Presidents Day 2012','Auto Dealer','Furniture Store',NULL);
INSERT INTO "missions" VALUES('Santa''s Swap','Bakery','Toy Store',NULL);
INSERT INTO "missions" VALUES('One Big Score','Bank','Casino',NULL);
INSERT INTO "missions" VALUES('Save The Planet','Bike Shop','Vegan Food',NULL);
INSERT INTO "missions" VALUES('Fathers Day 2012','Bike Shop','Animation Studio',NULL);
INSERT INTO "missions" VALUES('Summer School','Book Store','Tutoring Center',NULL);
INSERT INTO "missions" VALUES('The Dude Abides','Bowling Alley','Pub',NULL);
INSERT INTO "missions" VALUES('Beat the Heat','Coffee House','Pub','Soda Brewery');
INSERT INTO "missions" VALUES('Hot Trends','Coffee House','Record Shop',NULL);
INSERT INTO "missions" VALUES('April Fools 2012','Comedy Club','Billiard Hall',NULL);
INSERT INTO "missions" VALUES('Comic Convention','Comic Store','Pharmacy',NULL);
INSERT INTO "missions" VALUES('Valentines 2012','Day Spa','Floral Studio',NULL);
INSERT INTO "missions" VALUES('Mothers Day 2012','Day Spa','Womens Fashion',NULL);
INSERT INTO "missions" VALUES('Award Night','Dentists Office','Barber Shop',NULL);
INSERT INTO "missions" VALUES('On The Beat','Diner','Donut Shop',NULL);
INSERT INTO "missions" VALUES('Team Tiny','Doctors Office','Health Club',NULL);
INSERT INTO "missions" VALUES('Thanksgiving Feast','Fancy Cuisine','Travel Agency',NULL);
INSERT INTO "missions" VALUES('Prom Night','Floral Studio','Mens Fashion',NULL);
INSERT INTO "missions" VALUES('Spring Time','Floral Studio','Tattoo Parlor',NULL);
INSERT INTO "missions" VALUES('First Apartment','Furniture Store','Pottery Studio',NULL);
INSERT INTO "missions" VALUES('Superstar','Graphic Design','Record Shop',NULL);
INSERT INTO "missions" VALUES('Frog Fundraiser','Museum','Fancy Cuisine',NULL);
INSERT INTO "missions" VALUES('New Years 2012','Night Club','Health Club',NULL);
INSERT INTO "missions" VALUES('Nasty Bug','Pharmacy','Diner',NULL);
INSERT INTO "missions" VALUES('A Baby Is Born','Photo Studio','Toy Store',NULL);
INSERT INTO "missions" VALUES('Mars Curiosity','Planetarium','Laboratory',NULL);
INSERT INTO "missions" VALUES('Earth Day 2012','Plant Nursery','Recycling',NULL);
INSERT INTO "missions" VALUES('Last Night','Pub','Tattoo Parlor',NULL);
INSERT INTO "missions" VALUES('A Bit Fishy','Sushi Bar','Mexican Food',NULL);
INSERT INTO "missions" VALUES('A Day At The Beach','Shoe Store','Volleyball Club','Frozen Yogurt');
INSERT INTO "missions" VALUES('Back To Wiz School','Fortune Teller','Laboratory','Book Store');
INSERT INTO "missions" VALUES('Baseball Playoffs','Pub','Cineplex',NULL);
INSERT INTO "missions" VALUES('Bithoven''s Symphony','Wood Shop','Music Store',NULL);
INSERT INTO "missions" VALUES('Bit Trek TNG','Animation Studio','Tech Store',NULL);
INSERT INTO "missions" VALUES('Bits In Space','Toy Store','Planetarium',NULL);
INSERT INTO "missions" VALUES('Canadian Thanks 2012','Vegan Food','Fancy Cuisine',NULL);
INSERT INTO "missions" VALUES('Cinco De Mayo 2012','Mexican Food','Music Store',NULL);
INSERT INTO "missions" VALUES('Cowabunga','Laboratory','Martial Arts','Pizza Place');
INSERT INTO "missions" VALUES('Fire Drill','Security Office','Architect Office',NULL);
INSERT INTO "missions" VALUES('Labor Day 2012','Auto Dealer','Security Office',NULL);
INSERT INTO "missions" VALUES('London Games','Volleyball Club','Shoe Store','Racquetball');
INSERT INTO "missions" VALUES('Music Festival','Music Store','Recording Studio',NULL);
INSERT INTO "missions" VALUES('Myphone 5 Launch','Mapple Store','TV Studio',NULL);
INSERT INTO "missions" VALUES('One Mad Tea Party','Tea House','Bakery',NULL);
INSERT INTO "missions" VALUES('Pocket Planes','Travel Agency','Pub',NULL);
INSERT INTO "missions" VALUES('Self Defense','Martial Arts','Security Office',NULL);
INSERT INTO "missions" VALUES('St. Patty''s 2012','Tea House','Glass Studio',NULL);
INSERT INTO "missions" VALUES('Summer Vacation','Travel Agency','Scoops',NULL);
INSERT INTO "missions" VALUES('The Big Game','Tech Store','Pub',NULL);
INSERT INTO "missions" VALUES('The Heist','Security Office','Security Office',NULL);
INSERT INTO "missions" VALUES('Tiny Taxes','Tutoring Center','Bank',NULL);
INSERT INTO "missions" VALUES('Tower Watch','Security Office','Private Eye',NULL);
INSERT INTO "missions" VALUES('Wedding Season','Wedding Chapel','Floral Studio',NULL);
INSERT INTO "missions" VALUES('Mimecon 2012','Day Spa','Theater',NULL);
INSERT INTO "missions" VALUES('Halloween 2012','Chocolatier','Laboratory','Haunted House');
INSERT INTO "missions" VALUES('Election 2012','Ad Agency','TV Studio',NULL);
INSERT INTO "missions" VALUES('North Pole Recon','Private Eye','Fortune Teller',NULL);
INSERT INTO "missions" VALUES('Board Meeting','Sub Shop','Bakery','Coffee House');
INSERT INTO "missions" VALUES('Valentines 2014','Archery Range','Chocolatier',NULL);
INSERT INTO "missions" VALUES('National Pig Day','Hat Shop','Photo Studio',NULL);
INSERT INTO "missions" VALUES('St. Patty''s Day 2013','Bakery','Hat Shop',NULL);
INSERT INTO "missions" VALUES('Tower Taxes','Tutoring Center','Bank',NULL);
INSERT INTO "missions" VALUES('Arbor Day 2013','Plant Nursery','Sub Shop',NULL);
INSERT INTO "missions" VALUES('Cinco De Mayo 2013','Mexican Food','Music Store',NULL);
INSERT INTO "missions" VALUES('Mothers Day 2013','Womens Fashion','Jewelry Store','Day Spa');
INSERT INTO "missions" VALUES('Armed Forces Day 2013','Toy Store','Barber Shop','Security Office');
INSERT INTO "missions" VALUES('Memorial Day 2013','Music Store','Floral Studio',NULL);
INSERT INTO "missions" VALUES('JFK''s Birthday','Toy Store','TV Studio',NULL);
INSERT INTO "missions" VALUES('Feel the Earth','Bike Shop','Recycling','Recycling');
INSERT INTO "missions" VALUES('Flag Day 2013','Fabric Shop','Fabric Shop',NULL);
INSERT INTO "missions" VALUES('Fathers Day 2013','Tech Store','Animation Studio',NULL);
INSERT INTO "missions" VALUES('Solstice','Shoe Store','Park',NULL);
INSERT INTO "missions" VALUES('Independence Day ''13','Hot Dog Joint','Hat Shop',NULL);
INSERT INTO "missions" VALUES('Aboriginal Day ','Archery Range','Costume Shop',NULL);
INSERT INTO "missions" VALUES('Moon Day','Toy Store','Scoops',NULL);
INSERT INTO "missions" VALUES('Pioneer Day','Mechanic','Tech Store',NULL);
INSERT INTO "missions" VALUES('Book Lovers Day','Wood Shop','Book Store',NULL);
INSERT INTO "missions" VALUES('Summer Vacation ''13','Surf Shop','Smoothie Shop',NULL);
INSERT INTO "missions" VALUES('Relaxation Day','Day Spa','Candle Shop',NULL);
INSERT INTO "missions" VALUES('Aviation Day','Travel Agency','Pub',NULL);
INSERT INTO "missions" VALUES('Senior Citizens Day','Park','Womens Fashion','Mens Fashion');
INSERT INTO "missions" VALUES('Labor Day ''13','Plumber','Fire Station',NULL);
INSERT INTO "missions" VALUES('Programmers'' Day','Tech Store','Software Studio',NULL);
INSERT INTO "missions" VALUES('Oktoberfest ''13','Pub','Clockmaker',NULL);
INSERT INTO "missions" VALUES('Confucious Day','Martial Arts','Asian Cuisine',NULL);
INSERT INTO "missions" VALUES('World Vegetarian Day','Vegan Food','Plant Nursery',NULL);
INSERT INTO "missions" VALUES('Fire Prevention Day','Fire Station','Ad Agency',NULL);
COMMIT;
